data_settings:
  data_dir: "dataset"
  raw_data_dir: "raw_dataset"
  trimmed_data_dir: "trimmed_dataset"
  padded_data_dir: "padded_dataset"
  train_batch_size: 20
model_settings:
  batch_size: 4
  epochs: 1
  checkpoint_dir: "checkpoints"